name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  VCPKG_COMMIT_ID: 84bab45d415d22042bd0b9081aea57f362da3f35

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    env:
      VCPKG_TARGET_TRIPLET: x64-linux
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      USE_MERGED_VCPKG_MANIFEST: 1
      GEN: ninja
      DUCKDB_PLATFORM: linux_amd64

    steps:
      - name: Install required packages
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq ninja-build make gcc-multilib g++-multilib \
            zip unzip build-essential checkinstall curl libz-dev

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@v1.2.11
        with:
          key: ${{ github.job }}

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Configure OpenSSL for Rust
        run: |
          echo "OPENSSL_ROOT_DIR=$(pwd)/build/release/vcpkg_installed/x64-linux" >> $GITHUB_ENV
          echo "OPENSSL_DIR=$(pwd)/build/release/vcpkg_installed/x64-linux" >> $GITHUB_ENV
          echo "OPENSSL_USE_STATIC_LIBS=true" >> $GITHUB_ENV

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build extension
        run: make release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: unity_catalog-linux-amd64
          path: build/release/extension/unity_catalog/unity_catalog.duckdb_extension
          if-no-files-found: error

#  build-macos:
#    name: Build (macOS)
#    runs-on: macos-latest
#    env:
#      VCPKG_TARGET_TRIPLET: arm64-osx
#      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
#      USE_MERGED_VCPKG_MANIFEST: 1
#      GEN: ninja
#      DUCKDB_PLATFORM: osx_arm64
#
#    steps:
#      - name: Install required packages
#        run: brew install ninja
#
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#          submodules: 'true'
#
#      - name: Setup Ccache
#        uses: hendrikmuhs/ccache-action@v1.2.11
#        with:
#          key: ${{ github.job }}
#
#      - name: Setup vcpkg
#        uses: lukka/run-vcpkg@v11.1
#        with:
#          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
#
#      - name: Configure OpenSSL for Rust
#        run: |
#          echo "OPENSSL_ROOT_DIR=$(pwd)/build/release/vcpkg_installed/arm64-osx" >> $GITHUB_ENV
#          echo "OPENSSL_DIR=$(pwd)/build/release/vcpkg_installed/arm64-osx" >> $GITHUB_ENV
#          echo "OPENSSL_USE_STATIC_LIBS=true" >> $GITHUB_ENV
#
#      - name: Setup Rust
#        uses: dtolnay/rust-toolchain@stable
#
#      - name: Build extension
#        run: make release
#
#      - name: Upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: unity_catalog-macos-arm64
#          path: build/release/extension/unity_catalog/unity_catalog.duckdb_extension
#          if-no-files-found: error
